config/routes.rb
Translater::Application.routes.draw do
   resources :request_tasks do 
    resources :micro_tasks
   end
  devise_for :requesters do 
    match '/requester' => "request_tasks#index", :as => :requester_root
  end
  devise_for :users do
    match '/user' => "user#index", :as => :user_root
  end
  
  match 'micro_tasks/:id/change_status/:status' => 'micro_tasks#change_status', :as => "change_microtask_status"
  match 'micro_tasks/:id/translate/:status' => 'micro_tasks#translate', :as => "translate_microtask"
  match 'micro_tasks/:id/do_translate/:status' => 'micro_tasks#do_translate', :as => "do_translate_microtask"

  match 'micro_tasks/search' => 'micro_tasks#search', :as =>"search"

  match 'micro_tasks/:status' => 'micro_tasks#show_tasks', :as => "show_micro_tasks"
  root :to => "home#index"

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
   layout 'request_layout'
   
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
    <% content_for :aside do %>
      <aside id="sidebar" class="column">
      	<form class="quick_search">
      		<input type="text" value="Quick Search" onfocus="if(!this._haschanged){this.value=''};this._haschanged=true;">
      	</form>
      	<hr/>
      	<h3>Content</h3>
      	  <ul class="toggle">
      			<li class="icn_new_article"><a href="#">New Article</a></li>
      			<li class="icn_edit_article"><a href="#">Edit Articles</a></li>
      			<li class="icn_categories"><a href="#">Categories</a></li>
      			<li class="icn_tags"><a href="#">Tags</a></li>
      		</ul>
      	  </aside>
    <% end %>



<div id = "requester_login">
  <%= link_to 'Requester Login',new_requester_session_path %>
</div>
<div id = "user_login">
  <%= link_to 'Worker Login',new_user_session_path %>
</div>

app/views/home/requester_form.html.erb
<header><h3>Post New Article</h3></header>

<div class="module_content">
		<fieldset>
			<label>Post Title</label>
			<input type="text">
		</fieldset>
		<fieldset>
			<label>Content</label>
			<textarea rows="12"></textarea>
		</fieldset>
		<fieldset style="width:48%; float:left; margin-right: 3%;"> <!-- to make two field float next to one another, adjust values accordingly -->
			<label>Category</label>
			<select style="width:92%;">
				<option>Articles</option>
				<option>Tutorials</option>
				<option>Freebies</option>
			</select>
		</fieldset>
		<fieldset style="width:48%; float:left;"> <!-- to make two field float next to one another, adjust values accordingly -->
			<label>Tags</label>
			<input type="text" style="width:92%;">
		</fieldset><div class="clear"></div>
</div>