config/routes.rb
Translater::Application.routes.draw do
   resources :request_tasks do 
    resources :micro_tasks
   end
  devise_for :requesters do 
    match '/requester' => "request_tasks#index", :as => :requester_root
  end
  devise_for :users do
    match '/user' => "user#index", :as => :user_root
  end
  
  match 'micro_tasks/:id/change_status/:status' => 'micro_tasks#change_status', :as => "change_microtask_status"
  match 'micro_tasks/:id/translate/:status' => 'micro_tasks#translate', :as => "translate_microtask"
  match 'micro_tasks/:id/do_translate/:status' => 'micro_tasks#do_translate', :as => "do_translate_microtask"

  match 'micro_tasks/search' => 'micro_tasks#search', :as =>"search"

  match 'micro_tasks/:status' => 'micro_tasks#show_tasks', :as => "show_micro_tasks"
  root :to => "home#index"

end

app/models/micro_task.rb
class MicroTask < ActiveRecord::Base
  belongs_to :request_task
  belongs_to :user
  validate :translated_microtask, :presence => true
end

app/controllers/micro_tasks_controller.rb
class MicroTasksController < ApplicationController
  # GET /micro_tasks
  # GET /micro_tasks.json
  layout 'user_layout'
  def index
    @micro_tasks = MicroTask.where(:request_task_id=>params[:request_task_id]).paginate(:page => params[:page], :per_page => 20)
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @micro_tasks }
    end
  end
  def show_tasks
    @current_tasks = current_user.micro_tasks.where(:status =>params[:status]).paginate(:page => params[:page], :per_page => 10)
    respond_to do |format|
      format.html # show_tasks.html.erb
      format.json { render json: @current_tasks }
    end
  end
  def search
    lang_to = params[:micro_task][:to]
    lang_from = params[:micro_task][:from]
    if lang_to!='' && lang_from!=''
      task_ids = RequestTask.find(:all, :select=>'id', conditions:{:to=>lang_to, :from =>lang_from}).collect(&:id) 
      @filtered_tasks = MicroTask.where("request_task_id in (?)",task_ids).paginate(:page =>params[:page],:per_page =>10)
    else
      @filtered_tasks = MicroTask.where(:status => 'pending').paginate(:page => params[:page], :per_page => 10)
    end
    respond_to do |format|
      format.html
    end
  end
  def change_status
    @micro_task = MicroTask.find(params[:id])
    @micro_task.status = params[:status]
    respond_to do |format|
      if @micro_task.save
        if @micro_task.status == 'approved'
          worker_id = @micro_task.user_id
          @user = User.find(worker_id)
          @user.credit = @user.credit + @micro_task.credit
          @user.save
        end
        format.html {redirect_to request_task_micro_tasks_path(@micro_task.request_task_id)}
        #format.js
      end
    end 
  end
  def translate
    @micro_task = MicroTask.find(params[:id])
    @micro_task.status = params[:status]
    @micro_task.user_id = current_user.id
    respond_to do |format|
      if @micro_task.save
        format.html
      end
    end
  end
  def do_translate
    @micro_task = MicroTask.find(params[:id])
    flash[:alert] = "Translation task done"
    respond_to do |format|
      if @micro_task.update_attributes(params[:micro_task])
        @micro_task.status = params[:status]
        if @micro_task.save
          format.html{ redirect_to user_root_path }
        end
      end
    end
  end
end

app/helpers/micro_tasks_helper.rb
module MicroTasksHelper
end

app/views/micro_tasks/change_status.js.erb
  $('.task_status_<%=@micro_task.id %> a').html('Approved');
  $('.task_status1_<%=@micro_task.id %> a').html('')  

app/views/micro_tasks/index.html.erb
<h1>Listing Micro Tasks</h1>

<table>
  <tr>
    <th>Task</th>
    <th>Translation microtask</th>
    <th>Translated microtask</th>
    <th></th>
  </tr>
<% i = 0 %>
<% @micro_tasks.each do |micro_task| %>
  <tr>
    <td><%= i=i+1 %></td>
    <td><%= micro_task.translation_microtask %></td>
    <td><% if micro_task.translated_microtask == nil %>
       processing
       <%else%>
       <%=micro_task.translated_microtask %>
    <% end %></td>
    
    <% if micro_task.status == 'approved' %>
    <td> Approved </td>
    <td></td>
    <% elsif micro_task.status == 'done' %>
    <td class = "task_status_<%=micro_task.id%>"><%= link_to 'Approve', change_microtask_status_path(micro_task,'approved')%></td>
    <td class = "task_status1_<%=micro_task.id%>"><%= link_to 'Decline', change_microtask_status_path(micro_task,'pending')%></td>
    <% else %>
    <td></td>
    <td></td>
    <% end %>
  </tr>
<% end %>
</table>
<%= will_paginate @micro_tasks %>
<h2><%= link_to 'Back to main', request_tasks_path %></h2>

app/views/micro_tasks/search.html.erb
<h1>Tasks that need to be translated</h1>

<table class = "task_table">   
  <tr>
    <th>Task</th>
    <th>Translation Microtask</th>
    <th>Credit</th>
    <th><%= form_tag(search_path, :method => 'get') %> 
   <%= select("micro_task", "from", Language.all.collect {|lang| [ lang.language, lang.id ] }, {:include_blank => 'From'}) %> </th>
    <th><%= select("micro_task", "to", Language.all.collect {|lang| [ lang.language, lang.id ] }, {:include_blank => 'To'}) %></th>
    <th> <%= submit_tag("Search") %> </th>
  </tr>
<% i = 0 %>
<% @filtered_tasks.each do |micro_task| %>
  <tr>
    <td><%= i=i+1 %></td>
    <td><%= micro_task.translation_microtask %></td>
    <td><%= micro_task.credit.round(3) %></td>
    <td>
      <% lang_id=RequestTask.find(micro_task.request_task_id).from %>
      <%= Language.find(lang_id).language %>
    </td>
    <td><% lang_id=RequestTask.find(micro_task.request_task_id).to %>
     <%= Language.find(lang_id).language %></td>
    <td><%= link_to 'Translate text', translate_microtask_path(micro_task,'locked') %></td>
  </tr>
<% end %>
</table>

<br />
<%=link_to 'back', user_root_path %>
<%= will_paginate @filtered_tasks %>

app/views/micro_tasks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Task:</b>
  <%= @micro_task.task_id %>
</p>

<p>
  <b>Status:</b>
  <%= @micro_task.status %>
</p>

<p>
  <b>Credit:</b>
  <%= @micro_task.credit %>
</p>

<p>
  <b>Translation microtask:</b>
  <%= @micro_task.translation_microtask %>
</p>

<p>
  <b>Translated microtask:</b>
  <%= @micro_task.translated_microtask %>
</p>

<p>
  <b>Worker:</b>
  <%= @micro_task.worker_id %>
</p>


<%= link_to 'Edit', edit_request_task_micro_task_path(@micro_task) %> |
<%= link_to 'Back', request_task_micro_tasks_path %>

app/views/micro_tasks/show_tasks.html.erb
<h1>Listing Micro Tasks</h1>

<table>
  <tr>
    <th>Task</th>
    <th>Translation text</th>
    <th>Translated text</th>
    <th>credit</th>
  </tr>
<% i = 0 %>
<% @current_tasks.each do |micro_task| %>
  <tr>
    <td><%= i=i+1 %></td>
    <td><%= micro_task.translation_microtask %></td>
    <td><%=micro_task.translated_microtask %></td>
    <td><%=micro_task.credit.round(3) %></td>
  </tr>
<% end %>
</table>
<%= will_paginate @current_tasks %>

app/views/micro_tasks/translate.html.erb
<h1>Translate Micro task</h1>
<table>
  <tr>
    <td>
      <fieldset>
        <legend><h3>Text to be translated</h3></legend>
        <%= @micro_task.translation_microtask %>
      </fieldset>
      <b>Credit:</b>
      <%= @micro_task.credit %>
    </p>

  </td>
  <td>

    <%= form_for(@micro_task, :url => do_translate_microtask_path(@micro_task,'done')) do |f|%>
    <% if @micro_task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@micro_task.errors.count, "error") %> prohibited this micro_task from being saved:</h2>
      <ul>
        <% @micro_task.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
    <% end %>
    <div class="field">
      <%= f.label :translated_microtask %><br />
      <%= f.text_area :translated_microtask %>
    </div>
    <div class="actions">
      <%= f.submit("Save translation") %>
    </div>
    <% end %>
  </td>
</tr>

</table>
<%= link_to 'Back', user_root_path %>