config/routes.rb
Translater::Application.routes.draw do
   resources :request_tasks do 
    resources :micro_tasks
   end
  devise_for :requesters do 
    match '/requester' => "request_tasks#index", :as => :requester_root
  end
  devise_for :users do
    match '/user' => "user#index", :as => :user_root
  end
  
  match 'micro_tasks/:id/change_status/:status' => 'micro_tasks#change_status', :as => "change_microtask_status"
  match 'micro_tasks/:id/translate/:status' => 'micro_tasks#translate', :as => "translate_microtask"
  match 'micro_tasks/:id/do_translate/:status' => 'micro_tasks#do_translate', :as => "do_translate_microtask"

  match 'micro_tasks/search' => 'micro_tasks#search', :as =>"search"

  match 'micro_tasks/:status' => 'micro_tasks#show_tasks', :as => "show_micro_tasks"
  root :to => "home#index"

end

app/models/request_task.rb
class RequestTask < ActiveRecord::Base
  belongs_to :requester
  has_many :micro_tasks
  validates_numericality_of :budget, :greater_than => 10, :format => /^([1-9]\d{0,5}|0)(\.\d{1,2})?$/
  validates :translation_text, :length => { :minimum => 50 },
                               :format => { :with => /\w/ }
  validates :to, :from, :presence => true
  after_save :split_into_tasks
  private
  def split_into_tasks
    translation_micro_task = self.translation_text.split('.')
    size = translation_micro_task.size
    credit = self.budget/size
    credit = 0.8 * credit
    task_id = self.id
    status = "pending"
    i = 0
    while i< size
      translation_microtask = translation_micro_task[i]
      @request_task = RequestTask.find(task_id)
      @request_task.micro_tasks.create(:credit =>credit, :status =>status, :translation_microtask =>translation_microtask)
      #MicroTask.create(:task_id => task_id, :credit =>credit, :status => status, :translation_microtask => translation_microtask)
      i = i+1
    end
  end
end

app/controllers/request_tasks_controller.rb
class RequestTasksController < ApplicationController
  # GET /projects/new
   # GET /projects/new.json
   before_filter :authenticate_requester!
   def index
    @request_tasks = current_requester.request_tasks.paginate(:page => params[:page], :per_page => 4)
    respond_to do |format|
       format.html # index.html.erb
       format.json { render json: @request_tasks }
     end
   end
   def new
     @request_task = RequestTask.new
     respond_to do |format|
       format.html # new.html.erb
       format.json { render json: @request_task }
     end
   end
   def create
      @request_task = current_requester.request_tasks.new(params[:request_task])
      respond_to do |format|
        if check_credit_available
          @request_task.save 
          format.html { redirect_to @request_task, notice: 'New work is successfully created.' }
          format.json { render json: @request_task, status: :created, location: @request_task }
        else
          format.html { render action: "new" }
          format.json { render json: @request_task.errors, status: :unprocessable_entity }
        end
      end
    end
    def show
      @request_task = current_requester.request_tasks.find(params[:id])
      respond_to do |format|
        format.html # show.html.erb
        format.json { render json: @request_task }
      end
    end
    def destroy
     @request_task = current_requester.request_tasks.find(params[:id])
     @request_task.destroy
    end
    private 
    def check_credit_available
      if current_requester.credit < params[:request_task][:budget].to_f
        flash[:notice] = "You don't have sufficient balance to create new task"
        false
      else
        current_requester.credit = current_requester.credit - params[:request_task][:budget].to_f
        current_requester.save
      end
    end
end

app/helpers/request_tasks_helper.rb
module RequestTasksHelper
end

app/views/request_tasks/index.html.erb
<div id = "task_instruction">
<h3>Post your translation task to thousand workers<h3>
<h3>My total credits: <%= current_requester.credit.round(3) %></h3>
<h3><%= link_to 'Submit a new work', new_request_task_path %></h3>
</div>

<h1>Listing all translation works</h1>
<table class = "translation_tasks">
  <tr>
    <th>Translation Text</th>
    <th>From</th>
    <th>To</th>
    <th>Budget</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @request_tasks.each do |task| %>
  <tr>
    <td><%= task.translation_text %></td>
    <td><%= Language.find(task.from).language %></td>
    <td><%= Language.find(task.to).language %></td>
    <td><%= task.budget.round(3) %></td>
    <td><%= link_to 'See task', task %></td>
    <td><%= link_to 'Translation Progress', request_task_micro_tasks_path(task) %></td>
    <td><%= link_to 'Delete',  request_task_path(task), confirm: 'Are you sure?', :method => 'delete' %></td>
  </tr>
<% end %>
</table>
<%= will_paginate @request_tasks %>

app/views/request_tasks/new.html.erb
<fieldset>
  <legend><h2>Post text for translation</h2></legend>
  <%= form_for(@request_task) do |f| %>
  <% if @request_task.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@request_task.errors.count, "error") %> prohibited this destination from being saved:</h2>

    <ul>
      <% @request_task.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
  <% end %>
<div id = "form_field">
  <div class="field">
     <%= f.label :from %><br />
     <%= select("request_task", "from", Language.all.collect {|lang| [ lang.language, lang.id ] }, {:include_blank => 'Select Language'}) %>  
     </div>
  <div class="field">
    <%= f.label :translation_text %><br />
    <%= f.text_area :translation_text,:placeholder => "Minimum 50 characters" %>
  </div>
  <div class="field">
    <%= f.label :to %><br />
    <%= select("request_task", "to", Language.all.collect {|lang| [ lang.language, lang.id ] }, {:include_blank => 'Select Language'}) %>  
  </div>
  <div class="field">
    <%= f.label :budget %><br />
    <%= f.text_field :budget, :placeholder => "Minimum budget should be 10" %><br />
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
</div>
  <% end %>
</fieldset>

app/views/request_tasks/show.html.erb
<h1>My translation Work</h1>
<hr />
<table width="100%" class="work_table">
  <tr>
    <td>From</td>
    <td> 
    <%= Language.find(@request_task.from).language %></td>
  </tr>
  <tr>
    <td>To</td>
    <td> <%= Language.find(@request_task.to).language %></td>
  </tr>
  <tr>
    <td>Translation text</td>
    <td> <%= @request_task.translation_text %></td>
  </tr>
  <tr>
    <td>Budget</td>
    <td> <%= @request_task.budget %></td>
  </tr>
</table>

<br />
<%= link_to 'Back to main', request_tasks_path %>