config/routes.rb
Translater::Application.routes.draw do
   resources :request_tasks do 
    resources :micro_tasks
   end
  devise_for :requesters do 
    match '/requester' => "request_tasks#index", :as => :requester_root
  end
  devise_for :users do
    match '/user' => "user#index", :as => :user_root
  end
  
  match 'micro_tasks/:id/change_status/:status' => 'micro_tasks#change_status', :as => "change_microtask_status"
  match 'micro_tasks/:id/translate/:status' => 'micro_tasks#translate', :as => "translate_microtask"
  match 'micro_tasks/:id/do_translate/:status' => 'micro_tasks#do_translate', :as => "do_translate_microtask"

  match 'micro_tasks/search' => 'micro_tasks#search', :as =>"search"

  match 'micro_tasks/:status' => 'micro_tasks#show_tasks', :as => "show_micro_tasks"
  root :to => "home#index"

end

app/helpers/layout_helper.rb
# These helper methods can be called in your template to set variables to be used in the layout
# This module should be included in all views globally,
# to do so you may need to add this line to your ApplicationController
#   helper :layout
module LayoutHelper
  def title(page_title, show_title = true)
    content_for(:title) { h(page_title.to_s) }
    @show_title = show_title
  end

  def show_title?
    @show_title
  end

  def stylesheet(*args)
    content_for(:head) { stylesheet_link_tag(*args) }
  end

  def javascript(*args)
    content_for(:head) { javascript_include_tag(*args) }
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Translater</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag :application %>
  <%= csrf_meta_tags %>
</head>
<body>
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
<%= yield %>

</body>
</html>

app/views/layouts/mytheme.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for?(:title) ? yield(:title) : "Untitled" %></title>
    <%= stylesheet_link_tag "mytheme" %>
    <%= javascript_include_tag :defaults %>
    <%= csrf_meta_tag %>
    <%= yield(:head) %>
  </head>
  <body>
    <div id="container">
      <% flash.each do |name, msg| %>
        <%= content_tag :div, msg, :id => "flash_#{name}" %>
      <% end %>
      <%= content_tag :h1, yield(:title) if show_title? %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/layouts/request_layout.html.erb
<!doctype html>
<html lang="en">

<head>
	<meta charset="utf-8"/>

	<title>Welcome to TextTranslater.com</title>
  <%= stylesheet_link_tag "application" %>
  <%= javascript_include_tag :application %>
  <%= javascript_include_tag :jquery %>
  <%= csrf_meta_tags %>
</head>
<body>
  
	<header id="header">
		<hgroup>
			<h1 class="site_title"><a href="#">TextTranslator.com</a></h1>
		</hgroup>
	</header> <!-- end of header bar -->
	
	<section id="secondary_bar">
		<div class="user">
			<!-- <p>John Doe (<a href="#">3 Messages</a>)</p> -->
			<p></p>
			<!-- <a class="logout_user" href="#" title="Logout">Logout</a> -->
		</div>
		<div class="breadcrumbs_container">
		   <% if requester_signed_in? %>
			<article class="breadcrumbs">
        Welcome <%= current_requester.email %>   
			   <div class="breadcrumb_divider"></div></article>
			   	<article class="breadcrumbs">
     		   <%= link_to 'Logout', destroy_requester_session_path, :method => 'get' %> 
   			   <div class="breadcrumb_divider"></div></article>
     			    <% end %>
		</div>
	</section><!-- end of secondary bar -->
  <aside id="sidebar" class="column">
   	<% if requester_signed_in? %>
   	<h3>Requester</h3>
   	  <ul class="toggle">
   	    <li class="icn_new_article"><%= link_to 'All submitted tasks', request_tasks_path %></li>
   			<li class="icn_new_article"><%= link_to 'Submit a new work', new_request_task_path %></li>
   				<li class="icn_categories"><a href="#">My Credit: <%=current_requester.credit%></a></li>
   		</ul>
   		<% else%>
   	  <h3>TranslatorText.com</h3>
   	  <strong>Login to have more access</strong>
   		<% end %>
   	  </aside>
	<section id="main" class="column">
		<article class="module width_full">
			<header><h3>TextTranslator.com</h3></header>
			<div class="module_content">
				<article class="stats_graph">
				  <p class="notice"><%= notice %></p>
           <p class="alert"><%= alert %></p>
					<%=yield%>
				</article>	
				<div class="clear"></div>
			</div>
		</article><!-- end of stats article -->
		

		<div class="clear"></div>
		
		<article class="module width_full">
			<footer>
				<div class="submit_link">
					Designed by <a href = "#">Cloud factory Engineers</a>
			</footer>
		</article><!-- end of post new article -->
		<div class="spacer"></div>
	</section>


</body>

</html>

app/views/layouts/user_layout.html.erb
<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8"/>
  <title>Welcome to TextTranslator.com</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag :jquery %>
  <%= javascript_include_tag :tablesorter %>
  <%= javascript_include_tag :application %>
  <%= csrf_meta_tags %>
</head>
<body>
  <header id="header">
    <hgroup>
      <h1 class="site_title"><a href="#">TextTranslator.com</a></h1>
    </hgroup>
  </header> <!-- end of header bar -->
  <section id="secondary_bar">
    <div class="user">
      <!-- <p>John Doe (<a href="#">3 Messages</a>)</p> -->

    <p></p>

    </div>
    <div class="breadcrumbs_container">
      <% if user_signed_in? %> 
      <article class="breadcrumbs">
        Welcome <%= current_user.email %>   
        <div class="breadcrumb_divider"></div></article>
        <article class="breadcrumbs">
          <%= link_to 'Logout', destroy_user_session_path, :method=> 'get' %> 

          <div class="breadcrumb_divider"></div></article>
          <% end %>
        </div>
      </section><!-- end of secondary bar -->
      <aside id="sidebar" class="column">
        <% if user_signed_in? %>
        <h3>Worker</h3>
        <ul class="toggle">
          <li class="icn_new_article"><%= link_to 'Show all tasks', user_root_path %></li>
          <li class="icn_new_article"><%= link_to 'My completed tasks', show_micro_tasks_path('done') %></li>
          <li class="icn_edit_article"><%= link_to 'My approved tasks', show_micro_tasks_path('approved') %></li>
          <li class="icn_tags"><a href="#">Credits:<% if user_signed_in? %><%=current_user.credit.round(3) %><%end %></a></li>

        </ul>
        <% end %>
      </aside>
      <section id="main" class="column">
        <article class="module width_full">
          <header><h3>TextTranslator.com</h3></header>
          <div class="module_content">
            <article class="stats_graph">
              <p class="notice"><%= notice %></p>
               <p class="alert"><%= alert %></p>
              <%=yield %>
            </article>	
            <div class="clear"></div>
          </div>
        </article><!-- end of stats article -->


        <div class="clear"></div>

        <article class="module width_full">
          <footer>
            <div class="submit_link">
              Designed by <a href = "#">Cloudfactory Engineers</a>
            </footer>
          </article><!-- end of post new article -->
          <div class="spacer"></div>
        </section>


      </body>

      </html>